user:
  name_max_size: 20
  phone_max_size: 15
  user_number: 12
  number_user_follower: 3
  min_password_length: 6
  max_password_length: 20
book:
  book_length_max_size: 50
  number_book_page: 12
  description_max_length: 3000
  max_length_title: 20
  description_size: 30
category:
  category_max_size: 30
  number_category_page: 10
author:
  author_max_size: 30
  number_author_page: 10
  description_max_size: 1000
  description_size: 400
publisher:
  publisher_max_size: 40
  number_publisher_page: 10
request:
  number_request_page: 10
review:
  description_max_size: 500
